### PR TITLE
chore(deps): update dependencies and migrate to nx@16

### PR DESCRIPTION
**Pull request by peterhnm**
**Description**
Update dependencies and migrate to nx version 16.

**Checklist**
* Code is easy to understand
* No obvious errors or bugs
* CI/CD Pipelines did run successfully
* Tests were implemented
* Documentation was created

### CODE REVIEW

**Review by lmoesle — APPROVED** [review]
👍🏻 looks good.

**Comment by lmoesle** [comment]
I get in the console when I run e.g. `npm run build` a Nx Cloud Warning:

```
 >  NX   Nx Cloud Problems

   - Error when connecting to Nx Cloud. Code: ERR_BAD_REQUEST. Error: This workspace is more than a week old and is unclaimed. Workspaces must be claimed within 7 days of creation..
```

By upgrading from nx version 15 to 16 you can enable/disable nx cloud for the runners (https://github.com/nrwl/nx/issues/17119#issuecomment-1559830915). Did you setup an account for nx cloud or do you get this warning too?

**Comment by peterhnm** [comment]
> Did you setup an account for nx cloud or do you get this warning too?

Nah I get this error too but ignored it 😅.

**Comment by lmoesle** [comment]
> > Did you setup an account for nx cloud or do you get this warning too?
> 
> Nah I get this warning too but ignored it sweat_smile. I will disable it.

I will open an issue to evaluate setup up an nx account or removing the nx cloud runners.

**Pull request merged**
